//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helium.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helium.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 服务激活 的本地化字符串。
        /// </summary>
        public static string activate_function {
            get {
                return ResourceManager.GetString("activate_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap adb {
            get {
                object obj = ResourceManager.GetObject("adb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ADB功能 的本地化字符串。
        /// </summary>
        public static string adb_function {
            get {
                return ResourceManager.GetString("adb_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空调狗 的本地化字符串。
        /// </summary>
        public static string air_frozen {
            get {
                return ResourceManager.GetString("air_frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Helium 的本地化字符串。
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小黑屋 的本地化字符串。
        /// </summary>
        public static string black_room {
            get {
                return ResourceManager.GetString("black_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑阈 的本地化字符串。
        /// </summary>
        public static string brevent {
            get {
                return ResourceManager.GetString("brevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷机指令 的本地化字符串。
        /// </summary>
        public static string flash_function {
            get {
                return ResourceManager.GetString("flash_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冰箱 的本地化字符串。
        /// </summary>
        public static string ice_box {
            get {
                return ResourceManager.GetString("ice_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他功能 的本地化字符串。
        /// </summary>
        public static string other_function {
            get {
                return ResourceManager.GetString("other_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限狗 的本地化字符串。
        /// </summary>
        public static string permission_dog {
            get {
                return ResourceManager.GetString("permission_dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shizuku 的本地化字符串。
        /// </summary>
        public static string shizuku {
            get {
                return ResourceManager.GetString("shizuku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原生指令 的本地化字符串。
        /// </summary>
        public static string stock_function {
            get {
                return ResourceManager.GetString("stock_function", resourceCulture);
            }
        }
    }
}
