//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helium.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helium.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Helium, 一个ADB工具箱。 的本地化字符串。
        /// </summary>
        public static string about_text_line1 {
            get {
                return ResourceManager.GetString("about_text_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专为Windows 10 和 Windows 8.1 设计 的本地化字符串。
        /// </summary>
        public static string about_text_line2 {
            get {
                return ResourceManager.GetString("about_text_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap adb {
            get {
                object obj = ResourceManager.GetObject("adb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ADB功能 的本地化字符串。
        /// </summary>
        public static string adb_functions {
            get {
                return ResourceManager.GetString("adb_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空调狗 的本地化字符串。
        /// </summary>
        public static string airfrozen {
            get {
                return ResourceManager.GetString("airfrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Helium 的本地化字符串。
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池信息 的本地化字符串。
        /// </summary>
        public static string battery_info {
            get {
                return ResourceManager.GetString("battery_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小黑屋 的本地化字符串。
        /// </summary>
        public static string black_room {
            get {
                return ResourceManager.GetString("black_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑阈 的本地化字符串。
        /// </summary>
        public static string brevent {
            get {
                return ResourceManager.GetString("brevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ADB检查设备 的本地化字符串。
        /// </summary>
        public static string check_adb {
            get {
                return ResourceManager.GetString("check_adb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fastboot检查设备 的本地化字符串。
        /// </summary>
        public static string check_fastboot {
            get {
                return ResourceManager.GetString("check_fastboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 © sudo2u | MIT 许可 的本地化字符串。
        /// </summary>
        public static string copyright_info {
            get {
                return ResourceManager.GetString("copyright_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap dev {
            get {
                object obj = ResourceManager.GetObject("dev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap flash {
            get {
                object obj = ResourceManager.GetObject("flash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 刷机指令 的本地化字符串。
        /// </summary>
        public static string flash_functions {
            get {
                return ResourceManager.GetString("flash_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷写REC镜像 的本地化字符串。
        /// </summary>
        public static string flash_recovery {
            get {
                return ResourceManager.GetString("flash_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github Release 的本地化字符串。
        /// </summary>
        public static string github_release {
            get {
                return ResourceManager.GetString("github_release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github Repo 的本地化字符串。
        /// </summary>
        public static string github_repo {
            get {
                return ResourceManager.GetString("github_repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冰箱 的本地化字符串。
        /// </summary>
        public static string icebox {
            get {
                return ResourceManager.GetString("icebox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ico {
            get {
                object obj = ResourceManager.GetObject("ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 部署应用 的本地化字符串。
        /// </summary>
        public static string install_app {
            get {
                return ResourceManager.GetString("install_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动ADB窗口 的本地化字符串。
        /// </summary>
        public static string launch_adb_window {
            get {
                return ResourceManager.GetString("launch_adb_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动SHELL窗口 的本地化字符串。
        /// </summary>
        public static string launch_shell_window {
            get {
                return ResourceManager.GetString("launch_shell_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机型信息 的本地化字符串。
        /// </summary>
        public static string model_info {
            get {
                return ResourceManager.GetString("model_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他功能 的本地化字符串。
        /// </summary>
        public static string other_functions {
            get {
                return ResourceManager.GetString("other_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限狗 的本地化字符串。
        /// </summary>
        public static string permission_dog {
            get {
                return ResourceManager.GetString("permission_dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启至BL 的本地化字符串。
        /// </summary>
        public static string reboot_bootloader {
            get {
                return ResourceManager.GetString("reboot_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启至REC 的本地化字符串。
        /// </summary>
        public static string reboot_recovery {
            get {
                return ResourceManager.GetString("reboot_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启 的本地化字符串。
        /// </summary>
        public static string reboot_system {
            get {
                return ResourceManager.GetString("reboot_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录屏 的本地化字符串。
        /// </summary>
        public static string record_screen {
            get {
                return ResourceManager.GetString("record_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务激活 的本地化字符串。
        /// </summary>
        public static string service_functions {
            get {
                return ResourceManager.GetString("service_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shizuku 的本地化字符串。
        /// </summary>
        public static string shizuku {
            get {
                return ResourceManager.GetString("shizuku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截图 的本地化字符串。
        /// </summary>
        public static string take_screenshot {
            get {
                return ResourceManager.GetString("take_screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap verify {
            get {
                object obj = ResourceManager.GetObject("verify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
