//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helium.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helium.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap adb {
            get {
                object obj = ResourceManager.GetObject("adb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 ADB功能 的當地語系化字串。
        /// </summary>
        public static string adb_functions {
            get {
                return ResourceManager.GetString("adb_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 空调狗 的當地語系化字串。
        /// </summary>
        public static string airfrozen {
            get {
                return ResourceManager.GetString("airfrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 电池信息 的當地語系化字串。
        /// </summary>
        public static string battery_info {
            get {
                return ResourceManager.GetString("battery_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 小黑屋 的當地語系化字串。
        /// </summary>
        public static string black_room {
            get {
                return ResourceManager.GetString("black_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 黑阈 的當地語系化字串。
        /// </summary>
        public static string brevent {
            get {
                return ResourceManager.GetString("brevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ADB检查设备 的當地語系化字串。
        /// </summary>
        public static string check_adb {
            get {
                return ResourceManager.GetString("check_adb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 检查设备 的當地語系化字串。
        /// </summary>
        public static string check_device {
            get {
                return ResourceManager.GetString("check_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fastboot检查设备 的當地語系化字串。
        /// </summary>
        public static string check_fastboot {
            get {
                return ResourceManager.GetString("check_fastboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap dev {
            get {
                object obj = ResourceManager.GetObject("dev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap flash {
            get {
                object obj = ResourceManager.GetObject("flash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 刷机指令 的當地語系化字串。
        /// </summary>
        public static string flash_functions {
            get {
                return ResourceManager.GetString("flash_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刷写REC镜像 的當地語系化字串。
        /// </summary>
        public static string flash_recovery {
            get {
                return ResourceManager.GetString("flash_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 冰箱 的當地語系化字串。
        /// </summary>
        public static string icebox {
            get {
                return ResourceManager.GetString("icebox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ico {
            get {
                object obj = ResourceManager.GetObject("ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 部署应用 的當地語系化字串。
        /// </summary>
        public static string install_app {
            get {
                return ResourceManager.GetString("install_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 启动ADB窗口 的當地語系化字串。
        /// </summary>
        public static string launch_adb_window {
            get {
                return ResourceManager.GetString("launch_adb_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 启动SHELL窗口 的當地語系化字串。
        /// </summary>
        public static string launch_shell_window {
            get {
                return ResourceManager.GetString("launch_shell_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 机型信息 的當地語系化字串。
        /// </summary>
        public static string model_info {
            get {
                return ResourceManager.GetString("model_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 其他功能 的當地語系化字串。
        /// </summary>
        public static string other_functions {
            get {
                return ResourceManager.GetString("other_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 权限狗 的當地語系化字串。
        /// </summary>
        public static string permission_dog {
            get {
                return ResourceManager.GetString("permission_dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 拉取文件 的當地語系化字串。
        /// </summary>
        public static string pull_file {
            get {
                return ResourceManager.GetString("pull_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 推送文件 的當地語系化字串。
        /// </summary>
        public static string push_file {
            get {
                return ResourceManager.GetString("push_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重启至BL 的當地語系化字串。
        /// </summary>
        public static string reboot_bootloader {
            get {
                return ResourceManager.GetString("reboot_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重启至REC 的當地語系化字串。
        /// </summary>
        public static string reboot_recovery {
            get {
                return ResourceManager.GetString("reboot_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重启 的當地語系化字串。
        /// </summary>
        public static string reboot_system {
            get {
                return ResourceManager.GetString("reboot_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 录屏 的當地語系化字串。
        /// </summary>
        public static string record_screen {
            get {
                return ResourceManager.GetString("record_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 服务激活 的當地語系化字串。
        /// </summary>
        public static string service_functions {
            get {
                return ResourceManager.GetString("service_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shizuku 的當地語系化字串。
        /// </summary>
        public static string shizuku {
            get {
                return ResourceManager.GetString("shizuku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 截图 的當地語系化字串。
        /// </summary>
        public static string take_screenshot {
            get {
                return ResourceManager.GetString("take_screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap verify {
            get {
                object obj = ResourceManager.GetObject("verify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
